
services:
    scic_web_server:
        container_name: scic_web_server
        build:
            context: ./SCIC_BE
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"

                
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        networks:
        - productnetwork

    

networks:
  productnetwork:
    driver: bridge